name: "integration with github"
on: 
 push:
  branches: 
   -terraformInfra_master

jobs:
  terraform:
    name: "terraform init"
    runs-on: ubuntu-latest
    steps:
     - name: "checkout"
       uses: actions/checkout@master
     - name: "intialize terraform" 
       uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          TF_WORKSPACE: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
