name: "integration with github"
on: [push,pull_request]

jobs:
  terraform:
    name: "terraform init"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./main.tf
    steps:
     - name: "checkout"
       uses: actions/checkout@master
     - name: setup terraform
       uses: hashicorp/setup-terraform@v1
       with:
        terraform_version: 1.0.10
     - name: Terraform Init 
       id: init
       run: terraform init
